question_data = [
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The HTML5 standard was published in 2014.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The first computer bug was formed by faulty wires.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "FLAC stands for 'Free Lossless Audio Condenser'.",
     "correct_answer": "False"},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "All program codes have to be compiled into an executable file in order to be run. This file can "
                 "then be executed on any machine.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Linus Torvalds created Linux and Git.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The programming language 'Python' is based off a modified version of 'JavaScript'",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "AMD created the first consumer 64-bit processor.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "'HTML' stands for Hypertext Markup Language.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "hard",
     "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of "
                 "memory.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a "
                 "famous king of Hawaii.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In Chobits, Hideki found Chii in his apartment.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf "
                 "Children&quot; and &quot;The Boy and the Beast&quot;.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the "
                 "nickname Kyon.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of "
                 "level 6 in their abilities.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Gosho Aoyama Made This Series: (Detective Conan / Case Closed!)",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is "
                 "God.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The shotgun appears in every numbered Resident Evil game.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Donkey Kong was originally set to be a Popeye arcade game.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass/Poison type.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}
]
